files:
  include: app/assets/stylesheets/**/*.scss
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth:
    - 0
    - max-depth: 1
  border-zero:
    - 1
    - convention: 0
  brace-style:
    - 1
    - allow-single-: true
  class-name-format:
    - 2
    - convention: hyphenatedbem
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: false
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 1
    - convention: hyphenatedlowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: true
  mixin-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 1
  nesting-depth:
    - 2
    - max-depth: 5
  no-color-keywords: 1
  no-color-literals: 0
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: true
  no-trailing-zero: 1
  no-transition-all: 0
  no-url-protocols: 1
  no-vendor-prefixes:
    - 1
    - additional-identifiers: []
      excluded-identifiers: []
  placeholder-in-extend: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order:
    - 2
    - ignore-custom-properties: false
      order:
        - bottom
        - display
        - left
        - position
        - right
        - top
        - z-index
        -
        - align-content
        - align-items
        - align-self
        - flex
        - flex-basis
        - flex-direction
        - flex-flow
        - flex-grow
        - flex-shrink
        - flex-wrap
        - justify-content
        - order
        -
        - clear
        - clip
        - float
        - height
        - margin
        - margin-bottom
        - margin-bottom-collapse
        - margin-collapse
        - margin-left
        - margin-left-collapse
        - margin-right
        - margin-right-collapse
        - margin-top
        - margin-top-collapse
        - max-height
        - max-width
        - min-height
        - min-width
        - overflow
        - overflow-x
        - overflow-y
        - padding
        - padding-bottom
        - padding-left
        - padding-right
        - padding-top
        - width
        -
        - animation
        - animation-delay
        - animation-duration
        - animation-fill-mode
        - animation-iteration-count
        - animation-name
        - animation-play-state
        - animation-timing-function
        - appearance
        - backface-visibility
        - background
        - background-attachment
        - background-clip
        - background-color
        - background-image
        - background-position
        - background-repeat
        - background-size
        - border
        - border-bottom
        - border-bottom-color
        - border-bottom-left-radius
        - border-bottom-right-radius
        - border-bottom-style
        - border-bottom-width
        - border-collapse
        - border-color
        - border-image
        - border-left
        - border-left-color
        - border-left-style
        - border-left-width
        - border-radius
        - border-radius-bottomleft
        - border-radius-bottomright
        - border-radius-topleft
        - border-radius-topright
        - border-right
        - border-right-color
        - border-right-style
        - border-right-width
        - border-spacing
        - border-style
        - border-top
        - border-top-color
        - border-top-left-radius
        - border-top-right-radius
        - border-top-style
        - border-top-width
        - border-width
        - box-align
        - box-flex
        - box-orient
        - box-pack
        - box-shadow
        - box-sizing
        - color
        - content
        - cursor
        - direction
        - filter
        - font
        - font-family
        - font-size
        - font-smoothing
        - font-style
        - font-weight
        - hyphens
        - interpolation-mode
        - letter-spacing
        - line-height
        - list-style
        - list-style-image
        - list-style-position
        - list-style-type
        - marks
        - opacity
        - osx-font-smoothing
        - outline
        - outline-color
        - outline-offset
        - outline-style
        - outline-width
        - page
        - pointer-events
        - quotes
        - resize
        - set-link-source
        - size
        - speak
        - src
        - table-layout
        - text-align
        - text-decoration
        - text-indent
        - text-overflow
        - text-rendering
        - text-shadow
        - text-size-adjust
        - text-transform
        - transform
        - transition
        - transition-delay
        - transition-duration
        - transition-property
        - transition-timing-function
        - unicode-bidi
        - user-select
        - vertical-align
        - visibility
        - white-space
        - word-break
        - word-spacing
        - word-wrap
        - zoom
  property-units:
    - 1
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
      per-property: {}
  quotes:
    - 1
    - style: double
  shorthand-values:
    - 1
    - allowed-shorthands:
        - 1
        - 2
        - 3
        - 4
  single-line-per-selector: 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-for-property:
    - 0
    - properties: []
  variable-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 1
